[[plugins]]
repo = 'hachibeeDI/deoplete-ternjs'
hook_source = '''
"let g:deoplete#sources#ternjs#tern_bin = '/users/hanafusaryo/.nodebrew/node/v9.11.1/lib/node_modules/tern/bin/tern'
"let g:deoplete#sources#ternjs#timeout = 1
"let g:deoplete#sources#ternjs#types = 1
"let g:deoplete#sources#ternjs#depths = 1
"let g:deoplete#sources#ternjs#filetypes = [
"                \ 'jsx',
"                \ 'javascript.jsx',
"                \ 'vue',
"                \ 'javascript']
" Use deoplete.
let g:tern_request_timeout = 1
let g:tern_show_signature_in_pum = '0'  " This do disable full signature type on autocomplete

"Add extra filetypes
let g:tern#filetypes = [
                \ 'jsx',
                \ 'javascript.jsx',
                \ 'vue',
                \ 'javascript'
                \ ]
'''
