[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # vimヘルプ日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
if exists("*denite#custom#map")
    "denite時に使用するキーマップ
    "ESCキーでdeniteを終了
    call denite#custom#map('insert', '<esc>', '<denite:enter_mode:normal>', 'noremap')
    call denite#custom#map('normal', '<esc>', '<denite:quit>', 'noremap')
    "C-N,C-Pで上下移動
    call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
    call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
    "C-J,C-Kでsplitで開く, C-Tでタブで開く
    call denite#custom#map('insert', '<C-j>', '<denite:do_action:split>', 'noremap')
    call denite#custom#map('insert', '<C-k>', '<denite:do_action:vsplit>', 'noremap')
    call denite#custom#map('insert', '<C-t>', '<denite:do_action:tabopen>', 'noremap')
endif

" 以下はdenite起動時に使用するキーマップ
" バッファ一覧
noremap <C-P> :Denite buffer<CR>
" ファイル一覧
noremap <C-N> :Denite -buffer-name=file file<CR>
" 最近使ったファイルの一覧
noremap <C-Z> :Denite file_old<CR>
" カレントディレクトリ
noremap <C-C> :Denite file_rec<CR>
"バッファ一覧
nnoremap sB :<C-u>Denite buffer -buffer-name=file<CR>

"Denite でバッファ内検索 
nnoremap <silent> <expr><Space><C-f> ":<C-u>Denite line<CR>"
nnoremap <silent> <expr><Space>l ":<C-u>DeniteCursorWord line<CR>"
'''
