[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = '''
" Python2 のインターフェイスが有効じゃないよと都度警告を出してくれるので
" それを無効に
let g:jedi#force_py_version = 3
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_source = 'Shougo/deoplete.nvim'
